---
    - name: "To get the Admin sessions"
      dsmadmc:
        command: " select SESSION_ID from sessions where (SESSION_TYPE='{{ item }}') "
       # command: " select SESSION_ID from sessions "
        se: "{{ lookup('env', 'tsm_server_node') }}"
        id: "{{ lookup('env', 'tsm_app_user') }}"
        pa: "{{ lookup('env', 'tsm_app_password') }}"
        dataonly: true
        comma: true
      register: session_number 
      failed_when: ("No match found using this criteria" in session_number.stdout_lines)
      loop: "{{ session_type }}"
    
    - set_fact: 
        sess_num: "{{ sess_num|default([]) + item.stdout_lines  }}"
 #       sess_num: "{{ sess_num|default([]) }} + {{ item.stdout_lines | json_query(query) }}"
      loop: "{{ session_number.results }}"
      
 #     loop: "{{ session_number.stdout_lines }}"
    - debug: 
        msg: "{{session_number.results | map(attribute='stdout_lines') }}"
    #- debug:
     #   var: sess_num
 #   - debug:
 #       var:
 #         - session_number | type_debug
 #         - session_number.results
 #         - session_number.stdout_lines
   #       - sess_num


    - name: Print the process numbers
        debug:
          msg:  session number is {{sess_num}}
      failed_when: ("No match found using this criteria" in sess_num)   
      loop: "{{ sess_num }}"
